# Generated by Django 6.0.2 on 2026-02-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
