# Generated by Django 6.0.2 on 2026-03-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_name_product_unique_name_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns_hash', models.CharField(max_length=255, unique=True)),
                ('mapping_data', models.JSONField()),
            ],
        ),
    ]
